function [Timestamp, num_ues, IMSI, RNTI, VarName5,...
        slicing_enabled, slice_id, slice_prb, ...
        power_multiplier, scheduling_policy, VarName11, ...
        dl_mcs, dl_n_samples, dl_bufferbytes, tx_brateDownlinkMbps, tx_pktsDownlink, tx_errorsDownlink, dl_cqi, ...
        VarName19, ul_mcs, ul_n_samples, ul_bufferbytes, ...
        rx_brateUplinkMbps, rx_pktsUplink, rx_errorsUplink, ...
        ul_rssi, ul_sinr, phr, VarName29, sum_requested_prbs, ...
        sum_granted_prbs, VarName32, dl_pmi, dl_ri, ul_n, ul_turbo_iters ...
        ] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  AIRSTL050 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  AIRSTL050 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  airstl050 = importfile("/home/pietro/Documents/traffic-analysis/data/air_stl_050.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Sep-2022 10:27:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 36);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "num_ues", "IMSI", "RNTI", "VarName5", "slicing_enabled", "slice_id", "slice_prb", "power_multiplier", "scheduling_policy", "VarName11", "dl_mcs", "dl_n_samples", "dl_bufferbytes", "tx_brateDownlinkMbps", "tx_pktsDownlink", "tx_errorsDownlink", "dl_cqi", "VarName19", "ul_mcs", "ul_n_samples", "ul_bufferbytes", "rx_brateUplinkMbps", "rx_pktsUplink", "rx_errorsUplink", "ul_rssi", "ul_sinr", "phr", "VarName29", "sum_requested_prbs", "sum_granted_prbs", "VarName32", "dl_pmi", "dl_ri", "ul_n", "ul_turbo_iters"];
opts.VariableTypes = ["double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName5", "VarName11", "VarName19", "VarName29", "VarName32"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName5", "VarName11", "VarName19", "VarName29", "VarName32"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);








%% DAJE

% %% Import data from text file
% % Script for importing data from the following text file:
% %
% %    filename: /home/pietro/Documents/traffic-analysis/data/air_stl_050.csv
% %
% % Auto-generated by MATLAB on 22-Sep-2022 10:48:33
% 
% %% Set up the Import Options and import the data
% opts = delimitedTextImportOptions("NumVariables", 36);
% 
% % Specify range and delimiter
% opts.DataLines = [2, Inf];
% opts.Delimiter = ",";
% 
% % Specify column names and types
% opts.VariableNames = ["Timestamp", "num_ues", "IMSI", "RNTI", "VarName5", "slicing_enabled", "slice_id", "slice_prb", "power_multiplier", "scheduling_policy", "VarName11", "dl_mcs", "dl_n_samples", "dl_bufferbytes", "tx_brateDownlinkMbps", "tx_pktsDownlink", "tx_errorsDownlink", "dl_cqi", "VarName19", "ul_mcs", "ul_n_samples", "ul_bufferbytes", "rx_brateUplinkMbps", "rx_pktsUplink", "rx_errorsUplink", "ul_rssi", "ul_sinr", "phr", "VarName29", "sum_requested_prbs", "sum_granted_prbs", "VarName32", "dl_pmi", "dl_ri", "ul_n", "ul_turbo_iters"];
% opts.VariableTypes = ["double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "string", "double", "double", "double", "double"];
% 
% % Specify file level properties
% opts.ExtraColumnsRule = "ignore";
% opts.EmptyLineRule = "read";
% 
% % Specify variable properties
% opts = setvaropts(opts, ["VarName5", "VarName11", "VarName19", "VarName29", "VarName32"], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, ["VarName5", "VarName11", "VarName19", "VarName29", "VarName32"], "EmptyFieldRule", "auto");
% 
% % Import the data
% tbl = readtable("/home/pietro/Documents/traffic-analysis/data/air_stl_050.csv", opts);

%% Convert to output type
Timestamp = tbl.Timestamp;
num_ues = tbl.num_ues;
IMSI = tbl.IMSI;
RNTI = tbl.RNTI;
VarName5 = tbl.VarName5;
slicing_enabled = tbl.slicing_enabled;
slice_id = tbl.slice_id;
slice_prb = tbl.slice_prb;
power_multiplier = tbl.power_multiplier;
scheduling_policy = tbl.scheduling_policy;
VarName11 = tbl.VarName11;
dl_mcs = tbl.dl_mcs;
dl_n_samples = tbl.dl_n_samples;
dl_bufferbytes = tbl.dl_bufferbytes;
tx_brateDownlinkMbps = tbl.tx_brateDownlinkMbps;
tx_pktsDownlink = tbl.tx_pktsDownlink;
tx_errorsDownlink = tbl.tx_errorsDownlink;
dl_cqi = tbl.dl_cqi;
VarName19 = tbl.VarName19;
ul_mcs = tbl.ul_mcs;
ul_n_samples = tbl.ul_n_samples;
ul_bufferbytes = tbl.ul_bufferbytes;
rx_brateUplinkMbps = tbl.rx_brateUplinkMbps;
rx_pktsUplink = tbl.rx_pktsUplink;
rx_errorsUplink = tbl.rx_errorsUplink;
ul_rssi = tbl.ul_rssi;
ul_sinr = tbl.ul_sinr;
phr = tbl.phr;
VarName29 = tbl.VarName29;
sum_requested_prbs = tbl.sum_requested_prbs;
sum_granted_prbs = tbl.sum_granted_prbs;
VarName32 = tbl.VarName32;
dl_pmi = tbl.dl_pmi;
dl_ri = tbl.dl_ri;
ul_n = tbl.ul_n;
ul_turbo_iters = tbl.ul_turbo_iters;

%% Clear temporary variables
clear opts tbl

end